import { AuthProvider } from "@/context/AuthContext";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { bricolage, inter } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="sr" className={`${bricolage.variable} ${inter.variable}`}>      
        <body className="font-sans antialiased">
          <AuthProvider>
            <Toaster/>
            {children}
          </AuthProvider>

        </body>          
    </html>
  );
}
